language: node_js
node_js:
- 7
- 6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start 
script:
  - npm install && npm test
cache:
  directories:
    - node_modules